export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const AD_QUERY_ROUTE = '/ad_query'
export const AD_ITEM_ROUTE = '/ad_item'
export const REACT_APP_API_URL = 'http://91.215.169.233:5001/'
